services:

  knorozovapi_frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - knorozovapi_backend
  
  knorozovapi_backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=knorozovapi_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - knorozovapi_db_data:/data/db
    ports:
      - "27019:27017"
  
volumes:
  88bau_db_data:
  knorozovapi_db_data:
  bau_uploads:
